### ISSUE TITLE
Down Monitor Interface Not Detected

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/bro-install#12]
If a user runs the `gen-node-cfg.sh` and they have not brought their monitor interface up, it will not be available for selection.

**Comment by Zalgo2462** [comment]
If on debian, we could bring the interface up and add 
```
iface eth0 inet manual
      pre-up ifconfig $IFACE up
      post-down ifconfig $IFACE down
```
to `/etc/network/interfaces` where eth0 is the new interface

**Comment by ethack** [comment]
@william-stearns thoughts?  I know you specifically filter out down interfaces right now.  Is there any reason we couldn't consider those in the script and bring them up for the user?

**Comment by william-stearns** [comment]
https://github.com/activecm/bro-install/pull/13 gives the user a chance to switch to a different terminal to make the changes.  It also asks them if they want to continue.
